# Site settings
title: Rakib's Personal Website
email: rakib_hasan6@yahoo.com
description: Rakib's Learning & Blogs
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/

# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: rakib09
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/rakib09/rakib09.github.io/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/rakib09/
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: Rakib
#duoshuo_url: "https://rakib09.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: https-rakib09-github-io
disqus_url: "https://rakib09.github.io"
#########################################

# Build settings
markdown: kramdown


# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
